import dotenv from "dotenv";
dotenv.config();
const {
  NODE_ENV = "development",
  APP_PORT = 3000,
  DEBUG_MODE = false,
  DATABASE_USER,
  DATABASE_HOST,
  DATABASE_NAME,
  DATABASE_PASSWORD,
  DATABASE_PORT,
  JWT_SECRET
} = process.env;

export { NODE_ENV, APP_PORT, DEBUG_MODE,DATABASE_USER,DATABASE_HOST,DATABASE_NAME,DATABASE_PASSWORD,DATABASE_PORT,JWT_SECRET};
